#!/usr/bin/perl
use FindBin '$RealBin';
use lib "$RealBin/lib";
use local::lib "$RealBin/perllib";
use LogBot::BP;

use DateTime;

LogBot->init("$RealBin/logbot.conf");

my $cutoff = DateTime->now->add(days => -5)->ymd('');
foreach my $file (glob(LogBot->config->{data_path} . '/log/logbot-*')) {
    next unless $file =~ /-(\d+)\.log$/;
    my $date = $1;
    next if $date >= $cutoff;
    unlink($file);
}
