#!/usr/bin/perl
# post logrotation handler for all irc processes
use local::lib;
use v5.10;
use strict;
use warnings;

use FindBin qw( $RealBin );
use lib "$RealBin/lib";

BEGIN {
    $ENV{TZ} = 'UTC';
}

use LogBot::Config qw( load_all_configs );
use LogBot::Util qw( file_for slurp );

foreach my $config (values %{ load_all_configs(all => !!$ENV{DEBUG}) }) {
    my $file = file_for($config, 'pid', 'logbot-irc');
    next unless -e $file;
    chomp(my $pid = slurp($file));
    kill('USR2', $pid);
}
